"""init production db

Revision ID: b255e368d51c
Revises: 
Create Date: 2023-08-26 10:41:53.442319

"""
import sqlalchemy as sa

from alembic import op

CURRENT_TIMESTAMP_ = "(CURRENT_TIMESTAMP)"

LANGUAGES_ID_FK = "languages.id"

VOCABULARY_QUESTIONS_ID_FK = "vocabulary_questions.id"

# revision identifiers, used by Alembic.
revision = "b255e368d51c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vocabulary_questions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("question_text", sa.VARCHAR(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.Column("is_valid", sa.BOOLEAN(), nullable=True),
        sa.Column("prompt_id", sa.INTEGER(), nullable=False),
        sa.Column("language_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"],
            [LANGUAGES_ID_FK],
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["vocabulary_prompts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "languages",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("language_name", sa.VARCHAR(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("language_name"),
    )
    op.create_table(
        "user_info",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(), nullable=False),
        sa.Column("full_name", sa.VARCHAR(), nullable=False),
        sa.Column("nickname", sa.VARCHAR(), nullable=True),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("phone_number", sa.VARCHAR(length=20), nullable=False),
        sa.Column("gender", sa.VARCHAR(length=20), nullable=True),
        sa.Column("country", sa.VARCHAR(), nullable=True),
        sa.Column("language", sa.VARCHAR(), nullable=True),
        sa.Column("date_of_birth", sa.DATE(), nullable=True),
        sa.Column("picture", sa.VARCHAR(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="user_info_pkey"),
        sa.UniqueConstraint("email", name="user_info_email_key"),
        sa.UniqueConstraint("phone_number", name="user_info_phone_number_key"),
        sa.UniqueConstraint("user_id", name="user_info_user_id_key"),
    )
    op.create_table(
        "vocabulary_prompts",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("prompt", sa.VARCHAR(), nullable=False),
        sa.Column("level", sa.INTEGER(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.Column("is_valid", sa.BOOLEAN(), nullable=True),
        sa.Column("category_id", sa.INTEGER(), nullable=False),
        sa.Column("language_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            [LANGUAGES_ID_FK],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vocabulary_answer_translations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("translated_text", sa.VARCHAR(), nullable=True),
        sa.Column("translated_language_id", sa.INTEGER(), nullable=False),
        sa.Column("answer_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["vocabulary_answers.id"],
            name="vocabulary_answer_translations_answer_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["translated_language_id"],
            [LANGUAGES_ID_FK],
            name="vocabulary_answer_translations_translated_language_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="vocabulary_answer_translations_pkey"),
    )
    op.create_table(
        "choice_question_response",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("question_id", sa.INTEGER(), nullable=True),
        sa.Column("answer_selected_id", sa.INTEGER(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["answer_selected_id"],
            ["vocabulary_answers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            [VOCABULARY_QUESTIONS_ID_FK],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("category_name", sa.VARCHAR(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_info.user_id"], name="category_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="category_pkey"),
        sa.UniqueConstraint(
            "user_id", "category_name", name="uq_category_user_id_category_name"
        ),
    )
    op.create_table(
        "image_caption",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.VARCHAR(), nullable=False),
        sa.Column("image_bucket_path_key", sa.VARCHAR(), nullable=False),
        sa.Column("language_id", sa.INTEGER(), nullable=False),
        sa.Column("caption", sa.VARCHAR(), nullable=False),
        sa.Column(
            "time_created",
            sa.DATETIME(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.Column(
            "time_updated",
            sa.DATETIME(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            [LANGUAGES_ID_FK],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_info.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vocabulary_answers",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("answer_text", sa.VARCHAR(), nullable=False),
        sa.Column("is_correct", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text(CURRENT_TIMESTAMP_),
            nullable=True,
        ),
        sa.Column("question_id", sa.INTEGER(), nullable=False),
        sa.Column("language_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"],
            [LANGUAGES_ID_FK],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            [VOCABULARY_QUESTIONS_ID_FK],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "image_captions_translations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("translated_caption", sa.VARCHAR(), nullable=True),
        sa.Column("caption_id", sa.INTEGER(), nullable=False),
        sa.Column("translated_language_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["caption_id"],
            ["image_caption.id"],
            name="image_captions_translations_caption_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["translated_language_id"],
            [LANGUAGES_ID_FK],
            name="image_captions_translations_translated_language_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="image_captions_translations_pkey"),
    )
    op.create_table(
        "vocabulary_question_translations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("translated_text", sa.VARCHAR(), nullable=True),
        sa.Column("translated_language_id", sa.INTEGER(), nullable=False),
        sa.Column("question_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            [VOCABULARY_QUESTIONS_ID_FK],
            name="vocabulary_question_translations_question_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["translated_language_id"],
            [LANGUAGES_ID_FK],
            name="vocabulary_question_translations_translated_language_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="vocabulary_question_translations_pkey"),
    )
    op.create_table(
        "vocabulary_prompt_translations",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("translated_language_id", sa.INTEGER(), nullable=False),
        sa.Column("translated_text", sa.VARCHAR(), nullable=True),
        sa.Column("prompt_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["vocabulary_prompts.id"],
            name="vocabulary_prompt_translations_prompt_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["translated_language_id"],
            [LANGUAGES_ID_FK],
            name="vocabulary_prompt_translations_translated_language_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="vocabulary_prompt_translations_pkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    return None
