
name: Run tests & publish image to Dockerhub

on:
  release:
    types: [published]
    branches:
      - master
    tags:
      - "v*"

  push:
    branches:
      - master
    tags:
      - "v*"

  pull_request:
    branches:
      - master


jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install the Dependencies
        run: |
          echo "Installing the dependencies..."
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Check Linter
        run: |
          echo "Checking linter formatting..."
          make lint-check

      - name: Run Tests
        run: |
          echo "Running the tests..."
          cd app && python -m pytest -v -s
